let apple: number = 5;
let speed: String = "100km/hr";
let hasName: boolean = true;
let nullVar: null = null;
let undefinedVar: undefined = undefined;
let date: Date = new Date();
let color: string[] = ["red", "blue", "green"];
let numArray: number[] = [1, 2, 3];
let booleanArr: boolean[] = [true, false, true];
